--insert de geografia 

INSERT INTO paises (pais_nombre) VALUES ('México');
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Águascalientes', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Baja California', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Baja California Sur', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Campeche', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Chiapas', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Chihuahua', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Ciudad de México', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Coahuila', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Colima', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Durango', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Guanajuato', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Guerrero', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Hidalgo', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Jalisco', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('México', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Michoacán', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Morelos', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Nayarit', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Nuevo León', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Oaxaca', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Puebla', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Querétaro', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Quintana Roo', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('San Luis Potosí', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Sinaloa', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Sonora', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Tabasco', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Tamaulipas', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Tlaxcala', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Veracruz', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Yucatán', 1);
INSERT INTO estados (est_nombre, est_paisId) VALUES ('Zacatecas', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Aguascalientes', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Jesús María', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Calvillo', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Pabellón de Arteaga', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Asientos', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Rincón de Romos', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cosío', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San José de Gracia', 1);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tijuana', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mexicali', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ensenada', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Rosarito', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tecate', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Felipe', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Valle de Mexicali', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Maneadero', 2);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('La Paz', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cabo San Lucas', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San José del Cabo', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Loreto', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Santa Rosalía', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Todos Santos', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad Constitución', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mulegé', 3);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Francisco de Campeche', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad del Carmen', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Escárcega', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Champotón', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Calkiní', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Hecelchakán', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Candelaria', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Hopelchén', 4);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tuxtla Gutiérrez', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tapachula', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Cristóbal', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Comitán', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Palenque', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ocosingo', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Arriaga', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tonalá', 5);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Chihuahua', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad Juárez', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Delicias', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cuauhtémoc', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Parral', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nuevo Casas Grandes', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Meoqui', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Camargo', 6);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Álvaro Obregón', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Benito Juárez', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Coyoacán', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Gustavo A. Madero', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Iztapalapa', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Miguel Hidalgo', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlalpan', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Xochimilco', 7);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Saltillo', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Torreón', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Monclova', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Piedras Negras', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Acuña', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ramos Arizpe', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Frontera', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Matamoros', 8);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Colima', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Manzanillo', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tecomán', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Villa de Álvarez', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Armería', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Comala', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Coquimatlán', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cuauhtémoc', 9);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Durango', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Gómez Palacio', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Lerdo', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Santiago Papasquiaro', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Canatlán', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nuevo Ideal', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mapimí', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Pueblo Nuevo', 10);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('León', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Irapuato', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Celaya', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Salamanca', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guanajuato', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Silao', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Miguel de Allende', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Dolores Hidalgo', 11);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Acapulco', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Chilpancingo', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Iguala', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Taxco', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zihuatanejo', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlapa', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ometepec', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Coyuca', 12);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Pachuca', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tulancingo', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tula', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ixmiquilpan', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Actopan', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tepeji del Río', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Huejutla', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tizayuca', 13);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guadalajara', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zapopan', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlaquepaque', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tonalá', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Puerto Vallarta', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Lagos de Moreno', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tepatitlán', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Autlán', 14);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ecatepec', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Naucalpan', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlalnepantla', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Toluca', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nezahualcóyotl', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Metepec', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Atizapán', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Chalco', 15);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Morelia', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Uruapan', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zamora', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Pátzcuaro', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Lázaro Cárdenas', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Apatzingán', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Hidalgo', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Sahuayo', 16);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cuernavaca', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cuautla', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Jiutepec', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Temixco', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Yautepec', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Xochitepec', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zacatepec', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Puente de Ixtla', 17);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tepic', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Bahía de Banderas', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Xalisco', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Santiago Ixcuintla', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Compostela', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Acaponeta', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tecuala', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Blas', 18);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Monterrey', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Nicolás', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Pedro', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guadalupe', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Apodaca', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Escobedo', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Santa Catarina', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Linares', 19);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Oaxaca de Juárez', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Salina Cruz', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Juchitán', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tuxtepec', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Puerto Escondido', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Huatulco', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Huajuapan', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlaxiaco', 20);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Puebla', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tehuacán', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Atlixco', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cholula', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Martín Texmelucan', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zacatlán', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Izúcar', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Acatzingo', 21);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Querétaro', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Juan del Río', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('El Marqués', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Corregidora', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tequisquiapan', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ezequiel Montes', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Amealco', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Peñamiller', 22);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cancún', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Playa del Carmen', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cozumel', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tulum', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Chetumal', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Isla Mujeres', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Bacalar', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Puerto Morelos', 23);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Luis Potosí', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Soledad', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Matehuala', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Rioverde', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad Valles', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tamazunchale', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ébano', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tamuín', 24);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Culiacán', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mazatlán', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Los Mochis', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guasave', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Navolato', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Escuinapa', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('El Fuerte', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mocorito', 25);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Hermosillo', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad Obregón', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nogales', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('San Luis Río Colorado', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Navojoa', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guaymas', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Caborca', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Agua Prieta', 26);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Villahermosa', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Cárdenas', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Comalcalco', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Macuspana', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Centla', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Huimanguillo', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Jalpa', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tenosique', 27);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Reynosa', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Matamoros', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tampico', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ciudad Victoria', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nuevo Laredo', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Madero', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Altamira', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Río Bravo', 28);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlaxcala', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Apizaco', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Huamantla', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Chiautempan', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zacatelco', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Calpulalpan', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tlaxco', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Nanacamilpa', 29);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Veracruz', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Xalapa', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Coatzacoalcos', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Minatitlán', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Córdoba', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Orizaba', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Poza Rica', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Boca del Río', 30);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Mérida', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Valladolid', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Tizimín', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Progreso', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ticul', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Umán', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Kanasín', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Motul', 31);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Zacatecas', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Fresnillo', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Jerez', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Guadalupe', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Río Grande', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Sombrerete', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Ojocaliente', 32);
INSERT INTO ciudades (ciu_nombre, ciu_estId) VALUES ('Jalpa', 32);
